import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
  {
    customerClerkId: String,
    orderId: { type: String, required: true, unique: true }, // generated by razorpay
    userId: { type: String, required: true }, // Clerk User ID
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
    },

    cartItems: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Product",
          required: true,
        },
        quantity: { type: Number, required: true },
        color: { type: String },
        sizes: { type: String },
      },
    ],
    amount: { type: Number, required: true },
    currency: { type: String, required: true, default: "INR" },
    status: {
      type: String,
      required: true,
      enum: ["pending", "paid", "cancelled", "created"],
      default: "created",
    },
    review: [{ type: mongoose.Schema.Types.ObjectId, ref: "Review" }],
    payment: {
      paymentId: { type: String },
      razorpayOrderId: { type: String },
      razorpayPaymentId: { type: String },
      razorpaySignature: { type: String },
    },
  },
  { timestamps: true }
);

const Order = mongoose.models.Order || mongoose.model("Order", orderSchema);
export default Order;
